# Generated by Django 5.0 on 2023-12-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=256)),
                ('body', models.TextField(max_length=4096)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
